# Hold until the corresponding training run is complete, then release that proc.
# No GPU allocation is consumed while held.
# condor_submit_bid 2000 submit_emergence_capacity_locations.sub
universe = vanilla
executable = /bin/bash
arguments = run_emergence_locations.sh /fast/fdraye/toy_model_linear/emergence_$(size)_means_s$(seed) --out-dir /fast/fdraye/toy_model_linear/emergence_$(size)_locations_s$(seed)
initialdir = /lustre/home/fdraye/projects/toy_model_linear
request_gpus = 1
request_cpus = 4
request_memory = 32 GB
requirements = (CUDACapability == 9.0) && (Machine =!= "i101.internal.cluster.is.localnet") && (Machine =!= "g155.internal.cluster.is.localnet") && (Machine =!= "i205.internal.cluster.is.localnet") && (Machine =!= "i207.internal.cluster.is.localnet")
hold = True
+IsDocker = False
stream_output = True
stream_error = True
output = /fast/fdraye/toy_model_linear/logs/emergence_capacity_locations_$(Cluster).$(Process).out
error = /fast/fdraye/toy_model_linear/logs/emergence_capacity_locations_$(Cluster).$(Process).err
log = /fast/fdraye/toy_model_linear/logs/emergence_capacity_locations_$(Cluster).$(Process).log
queue size,seed from (
large 46
large 47
large 48
medium 46
medium 47
medium 48
)
