# Predeclared seeds include the three previous seeds, with seven additional seeds.
# condor_submit_bid 2000 submit_dom_multiseed.sub
universe = vanilla
executable = /bin/bash
arguments = run_dom_multiseed.sh $(seed)
initialdir = /lustre/home/fdraye/projects/toy_model_linear
request_gpus = 1
request_cpus = 4
request_memory = 32 GB
requirements = (CUDACapability == 9.0) && (Machine =!= "i101.internal.cluster.is.localnet") && (Machine =!= "g155.internal.cluster.is.localnet") && (Machine =!= "i205.internal.cluster.is.localnet") && (Machine =!= "i207.internal.cluster.is.localnet") && (Machine =!= "i106.internal.cluster.is.localnet")
+IsDocker = False
stream_output = True
stream_error = True
output = /fast/fdraye/toy_model_linear/logs/dom_multiseed_$(Cluster).$(Process).out
error = /fast/fdraye/toy_model_linear/logs/dom_multiseed_$(Cluster).$(Process).err
log = /fast/fdraye/toy_model_linear/logs/dom_multiseed_$(Cluster).$(Process).log
queue seed in 46,47,48,49,50,51,52,53,54,55
